// make index for these components
export {default as Footer} from './Footer';
export {default as Welcome} from './Welcome';
export {default as Nav} from './Nav';
export {default as ModalMarket} from './ModalMarket';
export {default as ModalNative} from './ModalNative';
export {default as CardNative} from './CardNative';
export {default as CardLeasedIn} from './CardLeasedIn';
export {default as CardLeasedOut} from './CardLeasedOut';
export {default as ModalLeasedIn} from './ModalLeasedIn';
export {default as ModalLeasedOut} from './ModalLeasedOut';